"""
data_pipeline.py
-----------------
Turns the raw file discovery from dataset_loader.py into ready-to-train
tf.data.Dataset objects. This module is the bridge between "what images
exist on disk" (dataset_loader.py) and "what a model.fit() call needs"
(Phase 4's train.py).

Responsibilities:
  1. Stratified train/validation/test splitting, cached to disk so every
     later phase (train, evaluate) sees the IDENTICAL split.
  2. Class-imbalance handling via computed class weights.
  3. Assembling the tf.data.Dataset pipeline: load -> preprocess ->
     (augment if training) -> batch -> prefetch.

A note on data leakage (documented, not silently ignored):
PlantVillage's "color" folder is known to contain multiple images derived
from the same original photographed leaf (lighting/rotation variants
generated by the dataset's original authors). A purely random image-level
split - which is what this module does, and what the vast majority of
published PlantVillage work does - can therefore place near-duplicates of
the same physical leaf in both train and test, inflating test accuracy
slightly. True leaf-level grouping would require per-image provenance
metadata that is not present in the public folder structure, so it is out
of scope for this academic project. This limitation is called out here so
it can be cited in the project report rather than presented as a hidden
assumption.
"""

import json
import random
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight

from src.augmentation import apply_augmentation, build_augmentation_pipeline
from src.config import config
from src.dataset_loader import build_class_index, discover_classes
from src.preprocessing import load_label_and_image, validate_image
from src.utils import ensure_dir, get_logger

logger = get_logger(__name__)


@dataclass
class SplitEntry:
    path: str
    label: int
    class_name: str


# ---------------------------------------------------------------------------
# Splitting
# ---------------------------------------------------------------------------
def _splits_cache_path(representation: str) -> Path:
    return Path(config.SPLITS_DIR) / f"splits_{representation}.json"


def build_splits(
    dataset_root: Optional[str] = None,
    representation: Optional[str] = None,
    train_split: Optional[float] = None,
    val_split: Optional[float] = None,
    test_split: Optional[float] = None,
    seed: Optional[int] = None,
    validate_images: bool = True,
    force_rebuild: bool = False,
) -> dict:
    """
    Build (or load a cached) stratified train/val/test split.

    Returns a dict:
        {
          "class_names": [...],                 # index-aligned with labels
          "representation": "color",
          "train": [SplitEntry-as-dict, ...],
          "val":   [...],
          "test":  [...],
          "skipped_corrupt": [path, ...],
        }

    Caching: results are saved to data/splits/splits_<representation>.json.
    If a cache file exists AND matches the requested ratios/seed, it is
    reused instead of rescanning the whole dataset (which is expensive on
    ~54k images). This guarantees Phase 4 training and Phase 5 evaluation
    operate on the exact same split, which is essential for evaluation
    numbers to be trustworthy.
    """
    dataset_root = dataset_root or config.DATASET_ROOT
    representation = representation or config.DEFAULT_REPRESENTATION
    train_split = train_split if train_split is not None else config.TRAIN_SPLIT
    val_split = val_split if val_split is not None else config.VAL_SPLIT
    test_split = test_split if test_split is not None else config.TEST_SPLIT
    seed = seed if seed is not None else config.RANDOM_SEED

    ratio_sum = round(train_split + val_split + test_split, 6)
    if ratio_sum != 1.0:
        raise ValueError(
            f"train/val/test splits must sum to 1.0, got {ratio_sum} "
            f"({train_split} + {val_split} + {test_split})"
        )

    cache_path = _splits_cache_path(representation)
    if cache_path.exists() and not force_rebuild:
        with open(cache_path) as f:
            cached = json.load(f)
        meta = cached.get("_meta", {})
        if (
            meta.get("train_split") == train_split
            and meta.get("val_split") == val_split
            and meta.get("test_split") == test_split
            and meta.get("seed") == seed
            and meta.get("dataset_root") == str(dataset_root)
        ):
            logger.info("Loaded cached split from %s", cache_path)
            return cached
        logger.info("Cached split config differs from request; rebuilding.")

    logger.info("Building fresh %s split for representation='%s' ...",
                f"{train_split:.0%}/{val_split:.0%}/{test_split:.0%}", representation)

    class_names = discover_classes(dataset_root, representation)
    class_to_idx = {name: i for i, name in enumerate(class_names)}
    class_index = build_class_index(dataset_root, representation)

    all_paths: List[str] = []
    all_labels: List[int] = []
    skipped_corrupt: List[str] = []

    for class_name, images in class_index.items():
        label = class_to_idx[class_name]
        for img_path in images:
            if validate_images:
                ok, reason = validate_image(img_path)
                if not ok:
                    skipped_corrupt.append(str(img_path))
                    logger.warning("Skipping invalid image %s: %s", img_path, reason)
                    continue
            all_paths.append(str(img_path))
            all_labels.append(label)

    if not all_paths:
        raise RuntimeError(
            f"No valid images found under {dataset_root}/{representation} after validation."
        )

    # Stratified split: first carve off "train", then split what's left
    # into val/test proportionally. Using sklearn's `stratify` argument
    # (rather than looping per class manually) guarantees every class's
    # train/val/test proportions match the requested ratios as closely as
    # integer counts allow, and rejects the split cleanly if any class has
    # too few images to stratify (a useful early warning of tiny classes).
    try:
        train_paths, temp_paths, train_labels, temp_labels = train_test_split(
            all_paths, all_labels,
            test_size=(val_split + test_split),
            random_state=seed,
            stratify=all_labels,
        )
        relative_test_size = test_split / (val_split + test_split)
        val_paths, test_paths, val_labels, test_labels = train_test_split(
            temp_paths, temp_labels,
            test_size=relative_test_size,
            random_state=seed,
            stratify=temp_labels,
        )
    except ValueError as e:
        # sklearn's own message ("least populated class has only N members")
        # is accurate but not obviously actionable for someone running the
        # CLI - translate it into a concrete fix.
        min_needed = max(2, round(1 / min(val_split, test_split)))
        raise ValueError(
            "Could not create a stratified train/val/test split because at "
            "least one class has too few images for the requested split "
            f"ratios (each class needs at least ~{min_needed} images).\n"
            f"Underlying error: {e}\n"
            "Fix options: remove/merge that class, add more images to it, "
            "or adjust TRAIN_SPLIT/VAL_SPLIT/TEST_SPLIT in src/config.py."
        ) from e

    def _to_entries(paths, labels):
        return [
            asdict(SplitEntry(path=p, label=l, class_name=class_names[l]))
            for p, l in zip(paths, labels)
        ]

    result = {
        "class_names": class_names,
        "representation": representation,
        "train": _to_entries(train_paths, train_labels),
        "val": _to_entries(val_paths, val_labels),
        "test": _to_entries(test_paths, test_labels),
        "skipped_corrupt": skipped_corrupt,
        "_meta": {
            "dataset_root": str(dataset_root),
            "train_split": train_split,
            "val_split": val_split,
            "test_split": test_split,
            "seed": seed,
            "num_classes": len(class_names),
            "total_images_used": len(all_paths),
            "num_corrupt_skipped": len(skipped_corrupt),
        },
    }

    ensure_dir(config.SPLITS_DIR)
    with open(cache_path, "w") as f:
        json.dump(result, f, indent=2)
    logger.info(
        "Split built: train=%d val=%d test=%d classes=%d corrupt_skipped=%d. Cached to %s",
        len(result["train"]), len(result["val"]), len(result["test"]),
        len(class_names), len(skipped_corrupt), cache_path,
    )
    return result


# ---------------------------------------------------------------------------
# Class imbalance handling
# ---------------------------------------------------------------------------
def compute_class_weights(train_entries: List[dict], num_classes: int) -> Dict[int, float]:
    """
    Compute per-class weights for use as `model.fit(..., class_weight=...)`
    in Phase 4.

    Strategy: sklearn's 'balanced' heuristic -
        weight[c] = n_samples / (n_classes * n_samples_in_class_c)
    so rare classes get proportionally larger gradient contribution per
    sample, counteracting PlantVillage's class-size imbalance without
    duplicating any images (see config.CLASS_WEIGHT_STRATEGY docstring for
    why this is preferred over oversampling for this dataset).
    """
    labels = np.array([e["label"] for e in train_entries])
    present_classes = np.unique(labels)

    weights = compute_class_weight(
        class_weight=config.CLASS_WEIGHT_STRATEGY,
        classes=present_classes,
        y=labels,
    )
    class_weights = {int(c): float(w) for c, w in zip(present_classes, weights)}

    # Guard against any class that ended up with zero training samples
    # (shouldn't happen after stratified splitting, but fail loudly with a
    # useful default rather than crashing model.fit on a missing key).
    for c in range(num_classes):
        class_weights.setdefault(c, 1.0)

    return class_weights


# ---------------------------------------------------------------------------
# tf.data pipeline assembly
# ---------------------------------------------------------------------------
def build_tf_dataset(
    entries: List[dict],
    image_size: Optional[int] = None,
    batch_size: Optional[int] = None,
    augment: bool = False,
    shuffle: bool = False,
    seed: Optional[int] = None,
) -> tf.data.Dataset:
    """
    Turn a list of {"path", "label", "class_name"} entries (one split from
    build_splits) into a batched, prefetched tf.data.Dataset of
    (image, label) pairs ready for model.fit/evaluate/predict.

    - Labels are kept as plain integers (sparse), matching
      `sparse_categorical_crossentropy` used in Phase 4 - this avoids
      building a one-hot vector of size num_classes for every sample.
    - Augmentation is applied ONLY when augment=True, and should only ever
      be requested for the training split - val/test must reflect
      un-augmented, real data for evaluation numbers to be meaningful.
    """
    image_size = image_size or config.IMAGE_SIZE
    batch_size = batch_size or config.BATCH_SIZE
    seed = seed if seed is not None else config.RANDOM_SEED

    paths = [e["path"] for e in entries]
    labels = [e["label"] for e in entries]

    ds = tf.data.Dataset.from_tensor_slices((paths, labels))

    if shuffle:
        ds = ds.shuffle(buffer_size=len(paths), seed=seed, reshuffle_each_iteration=True)

    ds = ds.map(
        lambda p, l: load_label_and_image(p, l, image_size),
        num_parallel_calls=tf.data.AUTOTUNE,
    )

    if augment:
        aug_pipeline = build_augmentation_pipeline()
        ds = ds.map(
            lambda img, l: apply_augmentation(img, l, aug_pipeline),
            num_parallel_calls=tf.data.AUTOTUNE,
        )

    ds = ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return ds


def get_datasets(
    dataset_root: Optional[str] = None,
    representation: Optional[str] = None,
    image_size: Optional[int] = None,
    batch_size: Optional[int] = None,
    force_rebuild_splits: bool = False,
) -> Tuple[tf.data.Dataset, tf.data.Dataset, tf.data.Dataset, List[str], Dict[int, float]]:
    """
    One-call convenience function Phase 4's train.py will use:
        train_ds, val_ds, test_ds, class_names, class_weights = get_datasets()

    Returns train (shuffled + augmented), val (plain), test (plain),
    the ordered list of class names (index-aligned with integer labels),
    and the computed class weights dict for the training split.
    """
    splits = build_splits(
        dataset_root=dataset_root,
        representation=representation,
        force_rebuild=force_rebuild_splits,
    )
    image_size = image_size or config.IMAGE_SIZE
    batch_size = batch_size or config.BATCH_SIZE

    train_ds = build_tf_dataset(
        splits["train"], image_size, batch_size, augment=True, shuffle=True
    )
    val_ds = build_tf_dataset(
        splits["val"], image_size, batch_size, augment=False, shuffle=False
    )
    test_ds = build_tf_dataset(
        splits["test"], image_size, batch_size, augment=False, shuffle=False
    )

    class_weights = compute_class_weights(splits["train"], len(splits["class_names"]))

    return train_ds, val_ds, test_ds, splits["class_names"], class_weights
